#!/usr/bin/env bash
# This script is used configure a remote server with Nginx and customising
# and customising it's default html

sudo apt-get update

if ! dpkg-query -W nginx >/dev/null 2>&1; then
    sudo apt-get -y install nginx
else
    echo "Nginx is already installed."
fi

if ! sudo ufw status | grep -q 'Nginx HTTP'; then 
    sudo ufw allow 'Nginx HTTP'
fi
sudo ufw -y enable

sudo ufw status

sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www

echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html > /dev/null

sudo service nginx restart
